---
- hosts: production
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
    - name: Gather Facts
      setup:
  roles:
    - common
    - web
  remote_user: root
  vars: []
