---
- name: install apache/mysql
  apt: pkg={{ item }} state=latest install_recommends=no
  with_items:
    - apache2
    - mysql-server
    - libapache2-mod-php7.0
    - php7.0-mysql
    - nullmailer
  notify:
  - Start Apache
  register: apacheinstalled
- name: enable mod_rewrite
  when: apacheinstalled|success
  apache2_module: name=rewrite
  notify:
  - Reload Apache
- name: Disable default site
  when: apacheinstalled|success
  file: dest=/etc/apache2/sites-enabled/000-default.conf state=absent
  notify:
  - Reload Apache
- name: Configure nullmailer
  copy: src=remotes dest=/etc/nullmailer/remotes owner=root group=mail mode=0640
