---
- name: install apache/mysql
  apt: pkg={{ item }} state=latest install_recommends=no
  with_items:
    - mysql-server
    - php5
    - libapache2-mod-php5
    - libapache2-mod-auth-mysql
    - php5-mysql
  notify:
  - Start Apache
  register: apacheinstalled
- name: Create Web Root
  when: apacheinstalled|success
  file: dest=/var/www/louisvillemakesgames.org/htdocs mode=2775 state=directory owner=www-data group=www-data
  notify:
  - Reload Apahe
